# Generated by Django 5.2.8 on 2025-11-15 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labName', models.CharField(help_text='Dental laboratory name', max_length=100, null=True)),
                ('labPhone', models.CharField(blank=True, help_text='Contact phone', max_length=20, null=True)),
                ('labAddress', models.TextField(blank=True, help_text='Laboratory address', null=True)),
            ],
            options={
                'verbose_name': 'dental lab',
                'verbose_name_plural': 'dental labs',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialName', models.CharField(help_text='Material name', max_length=100, null=True)),
                ('materialDescription', models.TextField(blank=True, help_text='Material description', null=True)),
                ('materialStock', models.IntegerField(default=0, help_text='Stock quantity')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materials',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentDateTime', models.DateTimeField(auto_now_add=True, help_text='Date and time the payment was recorded')),
                ('paymentAmount', models.DecimalField(decimal_places=2, help_text='Amount paid', max_digits=10)),
                ('paymentMethod', models.CharField(blank=True, help_text='Payment method (cash, card, transfer...)', max_length=50, null=True)),
                ('paymentPlan', models.ForeignKey(help_text='Treatment plan associated with the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clinic.treatmentplan')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
    ]
