# Generated by Django 5.2.8 on 2025-11-05 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLab', models.CharField(help_text='Nombre del laboratorio dental', max_length=100)),
                ('telefonoLab', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20, null=True)),
                ('direccionLab', models.TextField(blank=True, help_text='Dirección del laboratorio', null=True)),
            ],
            options={
                'verbose_name': 'laboratorio dental',
                'verbose_name_plural': 'laboratorios dentales',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMaterial', models.CharField(help_text='Nombre del material', max_length=100)),
                ('descripcionMaterial', models.TextField(blank=True, help_text='Descripción del material', null=True)),
                ('stockMaterial', models.IntegerField(default=0, help_text='Cantidad en inventario')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiales',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraPayment', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró el pago')),
                ('montoPayment', models.DecimalField(decimal_places=2, help_text='Monto pagado', max_digits=10)),
                ('metodoPayment', models.CharField(blank=True, help_text='Método de pago (efectivo, tarjeta, transferencia...)', max_length=50, null=True)),
                ('planPayment', models.ForeignKey(help_text='Plan de tratamiento al que se asocia el pago', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clinic.treatmentplan')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
            },
        ),
    ]
