# Generated by Django 5.2.8 on 2025-11-05 22:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePatient', models.CharField(help_text='Ingrese el nombre del paciente', max_length=100)),
                ('apellidoPatient', models.CharField(help_text='Ingrese los apellidos del paciente', max_length=100)),
                ('fechaNacimientoPatient', models.DateField(blank=True, help_text='Ingrese la fecha de nacimiento del paciente', null=True)),
                ('telefonoPatient', models.CharField(blank=True, help_text='Ingrese el teléfono del paciente', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{7,15}$', 'Teléfono inválido.')])),
                ('direccionPatient', models.TextField(blank=True, help_text='Ingrese la dirección del paciente', null=True)),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='DentalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anamnesisHistory', models.TextField(blank=True, help_text='Ingrese la anamnesis del paciente', null=True)),
                ('pacienteHistory', models.OneToOneField(help_text='Seleccione el paciente al que pertenece esta historia', on_delete=django.db.models.deletion.CASCADE, related_name='dental_history', to='patients.patient')),
            ],
            options={
                'verbose_name': 'historia dental',
                'verbose_name_plural': 'historias dentales',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraAppointment', models.DateTimeField(help_text='Ingrese la fecha y hora de la cita')),
                ('motivoAppointment', models.TextField(blank=True, help_text='Ingrese el motivo o razón de la cita', null=True)),
                ('dentistaAppointment', models.ForeignKey(help_text='Seleccione el dentista de la cita', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic.dentist')),
                ('pacienteAppointment', models.ForeignKey(help_text='Seleccione el paciente de la cita', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
            },
        ),
    ]
