# Generated by Django 5.2.8 on 2025-11-15 22:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(help_text="Enter patient's first name", max_length=100)),
                ('patientLastName', models.CharField(help_text="Enter patient's last name", max_length=100)),
                ('patientBirthDate', models.DateField(blank=True, help_text="Enter patient's birth date", null=True)),
                ('patientPhone', models.CharField(blank=True, help_text="Enter patient's phone number", max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{7,15}$', 'Invalid phone number.')])),
                ('patientAddress', models.TextField(blank=True, help_text="Enter patient's address", null=True)),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
            },
        ),
        migrations.CreateModel(
            name='DentalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historyAnamnesis', models.TextField(blank=True, help_text='Enter patient anamnesis', null=True)),
                ('historyPatient', models.OneToOneField(help_text='Select the patient this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='dental_history', to='patients.patient')),
            ],
            options={
                'verbose_name': 'dental history',
                'verbose_name_plural': 'dental histories',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentDateTime', models.DateTimeField(help_text='Enter appointment date and time')),
                ('appointmentReason', models.TextField(blank=True, help_text='Enter reason for appointment', null=True)),
                ('appointmentDentist', models.ForeignKey(help_text='Select appointment dentist', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic.dentist')),
                ('appointmentPatient', models.ForeignKey(help_text='Select appointment patient', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'verbose_name': 'appointment',
                'verbose_name_plural': 'appointments',
            },
        ),
    ]
