# Generated by Django 5.2.8 on 2025-11-15 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dentistName', models.CharField(help_text="Enter the dentist's name", max_length=100)),
                ('dentistLastName', models.CharField(help_text="Enter the dentist's last name", max_length=100)),
                ('dentistSpecialty', models.CharField(blank=True, help_text="Dentist's specialty", max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'dentist',
                'verbose_name_plural': 'dentists',
            },
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toothNumber', models.CharField(help_text='Tooth number or code', max_length=10)),
                ('toothDescription', models.TextField(blank=True, help_text='Tooth description', null=True)),
            ],
            options={
                'verbose_name': 'tooth',
                'verbose_name_plural': 'teeth',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatmentName', models.CharField(help_text='Treatment name', max_length=100)),
                ('treatmentDescription', models.TextField(blank=True, help_text='Treatment description', null=True)),
                ('treatmentCost', models.DecimalField(blank=True, decimal_places=2, help_text='Treatment cost', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'treatment',
                'verbose_name_plural': 'treatments',
            },
        ),
        migrations.CreateModel(
            name='TreatmentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmQuantity', models.DecimalField(decimal_places=2, help_text='Quantity used', max_digits=10)),
            ],
            options={
                'verbose_name': 'treatment material',
                'verbose_name_plural': 'treatment materials',
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planStartDate', models.DateField(help_text='Plan start date')),
                ('planEndDate', models.DateField(blank=True, help_text='Expected end date (optional)', null=True)),
                ('planStatus', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', help_text='Current plan status', max_length=8)),
            ],
            options={
                'verbose_name': 'treatment plan',
                'verbose_name_plural': 'treatment plans',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedureDate', models.DateField(help_text='Date the procedure was performed')),
                ('procedureNotes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('procedureTooth', models.ForeignKey(blank=True, help_text='Tooth involved (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='clinic.tooth')),
                ('procedureTreatment', models.ForeignKey(help_text='Treatment performed', on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='clinic.treatment')),
            ],
            options={
                'verbose_name': 'procedure',
                'verbose_name_plural': 'procedures',
            },
        ),
    ]
