# Generated by Django 5.2.8 on 2025-11-05 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDentist', models.CharField(help_text='Ingrese el nombre del dentista', max_length=100)),
                ('apellidoDentist', models.CharField(help_text='Ingrese los apellidos del dentista', max_length=100)),
                ('especialidadDentist', models.CharField(blank=True, help_text='Especialidad del dentista', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'dentista',
                'verbose_name_plural': 'dentistas',
            },
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroTooth', models.CharField(help_text='Número o código del diente', max_length=10)),
                ('descripcionTooth', models.TextField(blank=True, help_text='Descripción del diente', null=True)),
            ],
            options={
                'verbose_name': 'diente',
                'verbose_name_plural': 'dientes',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTreatment', models.CharField(help_text='Nombre del tratamiento', max_length=100)),
                ('descripcionTreatment', models.TextField(blank=True, help_text='Descripción del tratamiento', null=True)),
                ('costoTreatment', models.DecimalField(blank=True, decimal_places=2, help_text='Costo del tratamiento', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'tratamiento',
                'verbose_name_plural': 'tratamientos',
            },
        ),
        migrations.CreateModel(
            name='TreatmentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadTm', models.DecimalField(decimal_places=2, help_text='Cantidad utilizada', max_digits=10)),
            ],
            options={
                'verbose_name': 'material por tratamiento',
                'verbose_name_plural': 'materiales por tratamiento',
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicioPlan', models.DateField(help_text='Fecha de inicio del plan')),
                ('fechaFinPlan', models.DateField(blank=True, help_text='Fecha de fin prevista (opcional)', null=True)),
                ('estadoPlan', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', help_text='Estado actual del plan', max_length=8)),
            ],
            options={
                'verbose_name': 'plan de tratamiento',
                'verbose_name_plural': 'planes de tratamiento',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaProcedure', models.DateField(help_text='Fecha en que se realizó el procedimiento')),
                ('observacionesProcedure', models.TextField(blank=True, help_text='Observaciones adicionales', null=True)),
                ('dienteProcedure', models.ForeignKey(blank=True, help_text='Diente intervenido (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='clinic.tooth')),
                ('tratamientoProcedure', models.ForeignKey(help_text='Tratamiento realizado', on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='clinic.treatment')),
            ],
            options={
                'verbose_name': 'procedimiento',
                'verbose_name_plural': 'procedimientos',
            },
        ),
    ]
