# Generated by Django 5.2.8 on 2025-11-15 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('inventory', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentmaterial',
            name='tmMaterial',
            field=models.ForeignKey(help_text='Material used', on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='inventory.material'),
        ),
        migrations.AddField(
            model_name='treatmentmaterial',
            name='tmTreatment',
            field=models.ForeignKey(help_text='Treatment that uses the material', on_delete=django.db.models.deletion.CASCADE, related_name='materiales_usados', to='clinic.treatment'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='planDentist',
            field=models.ForeignKey(help_text='Select the responsible dentist', on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='clinic.dentist'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='planPatient',
            field=models.ForeignKey(help_text='Select the patient', on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='procedurePlan',
            field=models.ForeignKey(help_text='Treatment plan this procedure belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='clinic.treatmentplan'),
        ),
        migrations.AlterUniqueTogether(
            name='treatmentmaterial',
            unique_together={('tmTreatment', 'tmMaterial')},
        ),
    ]
