# Generated by Django 5.2.8 on 2025-11-05 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('inventory', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentmaterial',
            name='materialTm',
            field=models.ForeignKey(help_text='Material empleado', on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='inventory.material'),
        ),
        migrations.AddField(
            model_name='treatmentmaterial',
            name='tratamientoTm',
            field=models.ForeignKey(help_text='Tratamiento que utiliza el material', on_delete=django.db.models.deletion.CASCADE, related_name='materiales_usados', to='clinic.treatment'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='dentistaPlan',
            field=models.ForeignKey(help_text='Seleccione el dentista responsable', on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='clinic.dentist'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='pacientePlan',
            field=models.ForeignKey(help_text='Seleccione el paciente', on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='planProcedure',
            field=models.ForeignKey(help_text='Plan de tratamiento al que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='clinic.treatmentplan'),
        ),
        migrations.AlterUniqueTogether(
            name='treatmentmaterial',
            unique_together={('tratamientoTm', 'materialTm')},
        ),
    ]
